# Generated by Django 4.0.6 on 2024-09-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_native_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_on',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='es', max_length=10),
        ),
    ]
