# Generated by Django 4.0.6 on 2024-09-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_native_language_customuser_working_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
