# Generated by Django 4.0.6 on 2024-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='working_on',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], default='es', max_length=10),
        ),
    ]
