# Generated by Django 4.0.6 on 2024-09-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_last_readwise_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_readwise_update',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='readwise_api_key',
        ),
    ]
