# Generated by Django 4.0.6 on 2024-09-06 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_last_readwise_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_readwise_update',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='readwise_api_key',
            field=models.CharField(blank=True, help_text='<a href="https://readwise.io/access_token" target="_blank">Generate API key here if you have an account.</a>', max_length=75, null=True),
        ),
    ]
