# Generated by Django 4.0.6 on 2024-09-07 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_last_readwise_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_readwise_update_articles',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
