# Generated by Django 4.0.6 on 2024-09-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_use_readwise_for_study_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_readwise_update_articles',
        ),
    ]
