# Generated by Django 4.0.6 on 2024-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_customuser_last_readwise_update_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='retrieve_native_language_from_readwise',
            field=models.BooleanField(default=False, help_text='By default, only foreign vocabulary is retrieved from Readwise.  Turn this on to import from your native language as well.'),
        ),
    ]
