# Generated by Django 4.0.6 on 2024-09-15 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_openai_llm_model_complex_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_readwise_update',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='last readwise update'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], default='en', max_length=10, verbose_name='native language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='retrieve_native_language_from_readwise',
            field=models.BooleanField(default=False, help_text='By default, only foreign vocabulary is retrieved from Readwise.  Turn this on to import from your native language as well.', verbose_name='retrieve native language from readwise'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='use_readwise_for_study_materials',
            field=models.BooleanField(default=False, help_text='Send study materials to <a href="https://readwise.io/" target="_blank">Readwise</a> (instead of email) if <a href="https://readwise.io/access_token" target="_blank">API key</a> is available.', verbose_name='use readwise for study materials'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='working_on',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], default='es', max_length=10, verbose_name='working on'),
        ),
    ]
