# Generated by Django 4.0.6 on 2024-09-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_native_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='use_raw_text',
            field=models.BooleanField(default=False, help_text='By default, raw text input is cleaned before saving a phrase.  To disable this, click here.', verbose_name='use raw text'),
        ),
    ]
