# Generated by Django 4.0.6 on 2024-09-05 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('cleaned_text', models.CharField(max_length=255)),
                ('example_sentence', models.CharField(max_length=255)),
                ('definition', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], help_text='If you leave this blank, we\'ll assume it\'s the current "working on" language.', max_length=10)),
                ('cosine_similarity', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cleaned_text')},
            },
        ),
    ]
