# Generated by Django 4.0.6 on 2024-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('ru', 'Russian')], default='es', max_length=10)),
                ('cosine_similarity', models.FloatField()),
            ],
        ),
    ]
