# Generated by Django 4.0.6 on 2024-09-06 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_alter_phrase_language'), ('main', '0003_alter_phrase_cosine_similarity'), ('main', '0004_alter_phrase_text'), ('main', '0005_alter_phrase_cleaned_text'), ('main', '0006_alter_phrase_language'), ('main', '0007_phrase_que_score'), ('main', '0008_phrase_noise'), ('main', '0009_remove_phrase_noise_remove_phrase_que_score')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Raw text')),
                ('cleaned_text', models.CharField(max_length=255, verbose_name='Phrase')),
                ('example_sentence', models.CharField(max_length=255)),
                ('definition', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], help_text='"working on" language if blank', max_length=10)),
                ('cosine_similarity', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cleaned_text')},
            },
        ),
    ]
