# Generated by Django 4.0.6 on 2024-09-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], help_text='"working on" language if blank', max_length=10),
        ),
    ]
