# Generated by Django 4.0.6 on 2024-09-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0009_remove_phrase_noise_remove_phrase_que_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], help_text='Dectected from text if blank', max_length=10),
        ),
    ]
