# Generated by Django 4.0.6 on 2024-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='cosine_similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
