# Generated by Django 4.0.6 on 2024-09-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_phrase_cosine_similarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='phrase',
            new_name='text',
        ),
    ]
