# Generated by Django 4.0.6 on 2024-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_phrase_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='cosine_similarity',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
