# Generated by Django 4.0.6 on 2024-09-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_phrase_language_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='text',
            new_name='raw_text',
        ),
    ]
