# Generated by Django 4.0.6 on 2024-09-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_phrase_phrase_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
