# Generated by Django 4.0.6 on 2024-09-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_text_phrase_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phrase',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
