# Generated by Django 4.0.6 on 2024-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_phrase_cosine_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Raw text'),
        ),
    ]
