# Generated by Django 4.0.6 on 2024-09-15 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_phrase_created_phrase_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='definition',
            field=models.CharField(max_length=255, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='example_sentence',
            field=models.CharField(max_length=255, verbose_name='example sentence'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], help_text='Dectected from text if blank', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
