# Generated by Django 4.0.6 on 2024-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_phrase_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='cleaned_text',
            field=models.CharField(max_length=255, verbose_name='Phrase'),
        ),
    ]
