# Generated by Django 4.0.6 on 2024-09-05 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_phrase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='phrase',
            unique_together={('user', 'text')},
        ),
    ]
