# Generated by Django 4.0.6 on 2024-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_phrase_cleaned_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('de', 'German'), ('la', 'Latin'), ('fr', 'French')], help_text='"working on" language if blank', max_length=10),
        ),
    ]
