# Generated by Django 4.0.6 on 2024-09-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_phrase_created_alter_phrase_definition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'verbose_name': 'Phrase', 'verbose_name_plural': 'Phrases'},
        ),
    ]
