# Generated by Django 4.0.6 on 2024-09-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_phrase_text_alter_phrase_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='es', max_length=10),
        ),
    ]
