# Generated by Django 4.0.6 on 2024-09-05 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_phrase_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='que_score',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5),
        ),
    ]
