# Generated by Django 4.0.6 on 2024-09-05 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_phrase_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='en', max_length=10)),
                ('working_on', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='es', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
