# Generated by Django 4.0.6 on 2024-09-05 23:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_phrase_que_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='noise',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5),
        ),
    ]
