# Generated by Django 4.0.6 on 2024-09-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_settings_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
