# Generated by Django 4.0.6 on 2024-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_phrase_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='sanity_check',
            field=models.TextField(default='', verbose_name='sanity check'),
            preserve_default=False,
        ),
    ]
