# Generated by Django 4.0.6 on 2024-09-05 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_alter_phrase_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='cosine_similarity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
