# Generated by Django 4.0.6 on 2024-09-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_phrase_cosine_similarity_alter_phrase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], help_text='If you leave this blank, we\'ll assume it\'s the current "working on" language.', max_length=10),
        ),
    ]
